### ISSUE TITLE
Add link in README to blogpost

### ISSUE THREAD

**Issue by unrevised6419** [vangware/react-pair#2]
I would like to recommend to add the blog post link in README

https://dev.to/vangware/the-paired-hook-pattern-4mo0

**Comment by loucyx** [comment]
Good suggestion! I'll update the README over the course of the day. Thanks!

**Comment by loucyx** [comment]
Fixed on https://github.com/vangware/react-pair/commit/c6037b958d060e1630b86f523622576e5bca4053
